widgetTheme=widget-themes/original
primaryColor=#ff5500
secondaryColor=#d81f08
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@domain.com
loadingLabel=Cargando...
loginError=El usuario o la contraseña son inválidos.
chatHeader=Chatea con nosotros
startInfo=Por favor, completa la siguiente para empezar a chatear
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Comenzar
backLabel=Atrás
initMessageBody=Hola, ¿cómo te puedo ayudar?
initMessageAuthor=Operador
chatInputLabel=Escribe tu pregunta
timeDaysAgo=día(s) atrás
timeHoursAgo=hora(s) atrás
timeMinutesAgo=minuto(s) atrás
timeSecondsAgo=segundo(s) atrás
offlineMessage=El operador se ha desconectado
toggleSoundLabel=Sonidos de chat
toggleScrollLabel=Auto scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Mostrar automáticamente
toggleFullscreenLabel=Alternar pantalla completa
endChatLabel=Terminar chat
endChatConfirmQuestion=¿Estás seguro?
endChatConfirm=Si
endChatCancel=Cancelar
contactHeader=Contáctanos
contactInfo=Todos los operadores están desconectados. Envíanos un e-mail con tu pregunta utilizando el formulario de abajo.
contactNameLabel=Tu nombre
contactMailLabel=Tu email
contactPasswordLabel=Tu contraseña
contactQuestionLabel=Tu pregunta
contactSendLabel=Enviar
contactSuccessHeader=Mensaje enviado
contactSuccessMessage=Tu pregunta ha sido enviada. ¡Gracias!
contactErrorHeader=Error
contactErrorMessage=Lo sentimos. Ocurrió un error al enviar tu pregunta
headerHeight=55
installed=1
